name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release-mate:
    name: Release Mate
    uses: ./.github/workflows/release-please.yml
    secrets:
      client-id: ${{ secrets.RELEASE_MATE_CLIENT_ID }}
      app-private-key: ${{ secrets.RELEASE_MATE_PRIVATE_KEY }}
