name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    uses: ./.github/workflows/release-please.yml
    secrets:
      app-id: ${{ secrets.RELEASE_BATON_APP_ID }}
      app-private-key: ${{ secrets.RELEASE_BATON_PRIVATE_KEY }}
